version: '3.8'

services:
  mysql:
    image: mysql:8.0.26
    container_name: db-for-go
    platform: linux/amd64

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION

    environment:
      MYSQL_ROOT_USER: ${ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}

    ports:
      - 3306:3306

    volumes:
      - db-volume:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  mysql-test:
    image: mysql:8.0.26
    container_name: db-for-go-test
    platform: linux/amd64

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION

    environment:
      MYSQL_ROOT_USER: ${ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${TEST_DB_NAME}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}

    ports:
      - 3307:3306 # 本番DBとポートを分ける

    volumes:
      - db-test-volume:/var/lib/mysql
      - ./initdb-test:/docker-entrypoint-initdb.d

volumes:
  db-volume:
  db-test-volume:
